creative_commons:
  license: by-nc-sa
  sidebar: true
  post: false
  language: deed.zh-hans
menu:
  home: / || home
  about: /about/ || user
  # tags: /tags/ || tags
  categories: /categories/ || th
  # archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
social:
  GitHub: https://github.com/ywwzwb || github

scheme: Gemini

utterances:
  enable: true
  repo: ywwzwb/ywwzwb.github.io # Github repository owner and name
  # Available values: pathname | url | title | og:title
  issue_term: title
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light