creative_commons:
  license: by-nc-sa
  sidebar: true
  post: false
  language: deed.zh-hans
menu:
  home: / || home
  about: /about/ || user
  # tags: /tags/ || tags
  categories: /categories/ || th
  # archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
social:
  GitHub: https://github.com/ywwzwb || github

scheme: Gemini